"""Preprocess the filtered Galaxy Zoo 2 dataset and generate stable splits.

This script performs deterministic preprocessing on the tabular dataset
generated by `scripts/data_acquisition/main.py` and optionally creates
reproducible train/validation/test split CSVs for downstream training.

Run from repository root:

    python scripts/preprocessing/main.py
    python scripts/preprocessing/main.py --drop-missing-files
    python scripts/preprocessing/main.py --force-rebuild-splits
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import Dict, Iterable, Tuple

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from galaxy_morphology_classification.training import (
    DEFAULT_RANDOM_STATE,
    DEFAULT_TEST_SPLIT,
    DEFAULT_VALIDATION_SPLIT,
    build_split_summary,
    save_dataset_splits,
    split_dataframe,
)

LOGGER = logging.getLogger(__name__)
REQUIRED_COLUMNS = ("objid", "gz2_class", "image_path")


def configure_logging() -> None:
    """Configure logging for preprocessing execution."""

    logging.basicConfig(
        level=logging.INFO,
        format="[%(asctime)s] [%(levelname)s] %(message)s",
    )


def get_project_root() -> Path:
    """Return the repository root path."""

    return PROJECT_ROOT


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description="Preprocess the filtered galaxy morphology dataset.",
    )
    parser.add_argument(
        "--input-csv",
        type=str,
        default=None,
        help="Input CSV path. Defaults to data/interim/merged_filtered.csv.",
    )
    parser.add_argument(
        "--output-csv",
        type=str,
        default=None,
        help="Output CSV path. Defaults to data/processed/merged_filtered_clean.csv.",
    )
    parser.add_argument(
        "--drop-missing-files",
        action="store_true",
        help="Drop rows whose image_path files are missing on disk.",
    )
    parser.add_argument(
        "--skip-splits",
        action="store_true",
        help="Skip the generation of train/validation/test split CSVs.",
    )
    parser.add_argument(
        "--splits-dir",
        type=str,
        default=None,
        help="Directory where split CSV files should be written.",
    )
    parser.add_argument(
        "--validation-size",
        type=float,
        default=DEFAULT_VALIDATION_SPLIT,
        help="Fraction of samples reserved for validation.",
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=DEFAULT_TEST_SPLIT,
        help="Fraction of samples reserved for blind test evaluation.",
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=DEFAULT_RANDOM_STATE,
        help="Random seed used for deterministic split generation.",
    )
    parser.add_argument(
        "--force-rebuild-splits",
        action="store_true",
        help="Overwrite existing split CSVs with a freshly generated split.",
    )
    return parser.parse_args()


def load_dataframe(csv_path: Path) -> pd.DataFrame:
    """Load the dataset from disk."""

    if not csv_path.exists():
        raise FileNotFoundError(
            f"Input dataset not found at {csv_path}. "
            "Run scripts/data_acquisition/main.py first."
        )

    LOGGER.info("Loading dataset from %s", csv_path)
    dataframe = pd.read_csv(csv_path)
    LOGGER.info("Loaded dataset shape: %s", dataframe.shape)
    return dataframe


def validate_required_columns(
    dataframe: pd.DataFrame,
    required_columns: Iterable[str] = REQUIRED_COLUMNS,
) -> None:
    """Validate that required columns exist."""

    missing_columns = [column for column in required_columns if column not in dataframe.columns]
    if missing_columns:
        raise KeyError(f"Missing required columns: {missing_columns}")


def preprocess_dataframe(dataframe: pd.DataFrame) -> Tuple[pd.DataFrame, Dict[str, int]]:
    """Apply deterministic preprocessing to the dataset."""

    validate_required_columns(dataframe)

    cleaned_df = dataframe[list(REQUIRED_COLUMNS)].copy()
    rows_input = len(cleaned_df)

    cleaned_df = cleaned_df.dropna(subset=list(REQUIRED_COLUMNS))
    rows_after_dropna = len(cleaned_df)

    cleaned_df["gz2_class"] = cleaned_df["gz2_class"].astype(str).str.strip()
    cleaned_df["image_path"] = cleaned_df["image_path"].astype(str).str.strip()

    cleaned_df = cleaned_df[
        (cleaned_df["gz2_class"] != "") & (cleaned_df["image_path"] != "")
    ]
    rows_after_empty_filter = len(cleaned_df)

    cleaned_df = cleaned_df.drop_duplicates(subset=list(REQUIRED_COLUMNS)).reset_index(drop=True)
    rows_after_dedup = len(cleaned_df)

    stats = {
        "rows_input": rows_input,
        "rows_removed_missing": rows_input - rows_after_dropna,
        "rows_removed_empty": rows_after_dropna - rows_after_empty_filter,
        "rows_removed_duplicates": rows_after_empty_filter - rows_after_dedup,
        "rows_output": rows_after_dedup,
    }
    return cleaned_df, stats


def drop_rows_with_missing_files(dataframe: pd.DataFrame) -> Tuple[pd.DataFrame, int]:
    """Drop rows whose image files do not exist on disk."""

    existing_mask = dataframe["image_path"].map(lambda path: Path(path).is_file())
    filtered_df = dataframe[existing_mask].reset_index(drop=True)
    removed_rows = int((~existing_mask).sum())
    return filtered_df, removed_rows


def save_dataframe(dataframe: pd.DataFrame, output_path: Path) -> None:
    """Save the cleaned dataframe to disk."""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    dataframe.to_csv(output_path, index=False)
    LOGGER.info("Preprocessed dataset saved to %s", output_path)


def main() -> None:
    """Run preprocessing workflow."""

    configure_logging()
    args = parse_args()

    project_root = get_project_root()
    default_input_path = project_root / "data" / "interim" / "merged_filtered.csv"
    default_output_path = project_root / "data" / "processed" / "merged_filtered_clean.csv"
    default_splits_dir = project_root / "data" / "processed" / "splits"

    input_csv = Path(args.input_csv) if args.input_csv else default_input_path
    output_csv = Path(args.output_csv) if args.output_csv else default_output_path
    splits_dir = Path(args.splits_dir) if args.splits_dir else default_splits_dir

    dataframe = load_dataframe(input_csv)
    cleaned_df, stats = preprocess_dataframe(dataframe)

    if args.drop_missing_files:
        cleaned_df, removed_rows = drop_rows_with_missing_files(cleaned_df)
        stats["rows_removed_missing_files"] = removed_rows
        stats["rows_output"] = len(cleaned_df)

    if cleaned_df.empty:
        raise ValueError("Preprocessing produced an empty dataset.")

    save_dataframe(cleaned_df, output_csv)

    if not args.skip_splits:
        split_paths_exist = all((splits_dir / name).exists() for name in ("train.csv", "validation.csv", "test.csv"))
        if split_paths_exist and not args.force_rebuild_splits:
            LOGGER.info(
                "Split files already exist at %s. Use --force-rebuild-splits to overwrite them.",
                splits_dir,
            )
        else:
            split_dataframes = split_dataframe(
                cleaned_df,
                validation_size=args.validation_size,
                test_size=args.test_size,
                random_state=args.random_state,
            )
            save_dataset_splits(
                split_dataframes,
                splits_dir,
                source_csv=output_csv,
                validation_size=args.validation_size,
                test_size=args.test_size,
                random_state=args.random_state,
            )
            LOGGER.info("Generated split summary: %s", build_split_summary(split_dataframes))

    LOGGER.info("Preprocessing summary: %s", stats)


if __name__ == "__main__":
    main()
