name: galaxy-morphology-classification
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - requests
  - pillow
  - jupyter
  - notebook
  - pip:
      - fastapi
      - httpx
      - kagglehub
      - pydantic
      - pytest
      - python-multipart
      - ruff
      - tensorflow
      - uvicorn
