"""Run exploratory data analysis for the filtered Galaxy Zoo 2 dataset.

This script:
1. Loads `data/interim/merged_filtered.csv`.
2. Prints a compact summary to the console.
3. Computes class distribution statistics.
4. Saves a class distribution bar chart to `docs/data/figures/class_distribution.png`.

Run from the repository root:

    python scripts/eda/main.py
"""

from __future__ import annotations

import logging
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

LOGGER = logging.getLogger(__name__)


def configure_logging() -> None:
    """Configure logging for the EDA workflow."""
    logging.basicConfig(
        level=logging.INFO,
        format="[%(asctime)s] [%(levelname)s] %(message)s",
    )


def get_project_root() -> Path:
    """Return the repository root path."""
    return Path(__file__).resolve().parents[2]


def load_filtered_dataset(csv_path: Path) -> pd.DataFrame:
    """Load the filtered dataset generated by the acquisition pipeline.

    Parameters
    ----------
    csv_path : Path
        Path to `merged_filtered.csv`.

    Returns
    -------
    pd.DataFrame
        Loaded dataset.
    """
    if not csv_path.exists():
        raise FileNotFoundError(
            f"Filtered dataset not found at {csv_path}. "
            "Run scripts/data_acquisition/main.py first."
        )

    LOGGER.info("Loading filtered dataset from %s", csv_path)
    dataframe = pd.read_csv(csv_path)
    LOGGER.info("Filtered dataset shape: %s", dataframe.shape)
    return dataframe


def print_basic_summary(df: pd.DataFrame) -> None:
    """Print a compact exploratory summary to the terminal.

    Parameters
    ----------
    df : pd.DataFrame
        Filtered dataset with at least `objid`, `gz2_class`, and `image_path`.
    """
    print("\n=== Dataset Shape ===")
    print(df.shape)

    print("\n=== Head ===")
    print(df.head())

    print("\n=== Data Types ===")
    print(df.dtypes)

    print("\n=== Missing Values ===")
    print(df.isnull().sum())

    if "gz2_class" in df.columns:
        print("\n=== Class Distribution ===")
        print(df["gz2_class"].value_counts())


def compute_class_distribution(df: pd.DataFrame) -> pd.Series:
    """Compute the class distribution of the target variable.

    Parameters
    ----------
    df : pd.DataFrame
        Input dataset.

    Returns
    -------
    pd.Series
        Frequency counts per class.
    """
    if "gz2_class" not in df.columns:
        raise KeyError("The dataset does not contain the 'gz2_class' column.")

    return df["gz2_class"].value_counts()


def save_class_distribution_plot(class_counts: pd.Series, output_path: Path) -> None:
    """Save a bar chart showing class frequencies.

    Parameters
    ----------
    class_counts : pd.Series
        Series indexed by class name with frequency counts.
    output_path : Path
        Destination PNG file.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(10, 6))
    class_counts.plot(kind="bar")
    plt.title("Galaxy Morphology Class Distribution")
    plt.xlabel("Morphology Class")
    plt.ylabel("Number of Samples")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()

    LOGGER.info("Class distribution figure saved to %s", output_path)


def main() -> None:
    """Run the exploratory data analysis workflow."""
    configure_logging()

    project_root = get_project_root()
    processed_dataset_path = project_root / "data" / "processed" / "merged_filtered_clean.csv"
    dataset_path = (
        processed_dataset_path
        if processed_dataset_path.exists()
        else project_root / "data" / "interim" / "merged_filtered.csv"
    )
    output_figure_path = project_root / "docs" / "data" / "figures" / "class_distribution.png"

    dataframe = load_filtered_dataset(dataset_path)
    print_basic_summary(dataframe)

    class_counts = compute_class_distribution(dataframe)
    save_class_distribution_plot(class_counts, output_figure_path)

    LOGGER.info("EDA workflow completed successfully.")


if __name__ == "__main__":
    main()
