"""Training data pipeline utilities for galaxy morphology classification.

This module provides reusable utilities to:
- load the filtered dataset produced during data acquisition,
- build class-to-index mappings,
- split the dataset into training and validation subsets,
- construct TensorFlow datasets ready for model training.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, Sequence, Tuple

import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split

LOGGER = logging.getLogger(__name__)

IMG_SIZE: Tuple[int, int] = (128, 128)


def get_project_root() -> Path:
    """Return the repository root path.

    This module is expected to live under:
        <repo_root>/src/galaxy_morphology_classification/training/__init__.py
    """
    return Path(__file__).resolve().parents[3]


def load_filtered_dataframe() -> pd.DataFrame:
    """Load the filtered dataset generated by the data acquisition stage.

    Returns
    -------
    pd.DataFrame
        DataFrame containing at least the following columns:
        - objid
        - gz2_class
        - image_path
    """
    csv_path = get_project_root() / "data" / "interim" / "merged_filtered.csv"

    if not csv_path.exists():
        raise FileNotFoundError(
            f"Filtered dataset not found at {csv_path}. "
            "Run scripts/data_acquisition/main.py first."
        )

    dataframe = pd.read_csv(csv_path)
    return dataframe


def build_class_mappings(df: pd.DataFrame) -> Tuple[Dict[str, int], Dict[int, str]]:
    """Build forward and reverse mappings between class names and integer labels.

    Parameters
    ----------
    df : pd.DataFrame
        Input DataFrame containing the `gz2_class` column.

    Returns
    -------
    Tuple[Dict[str, int], Dict[int, str]]
        A tuple containing:
        - class_to_index: mapping from class name to numeric label
        - index_to_class: reverse mapping from numeric label to class name
    """
    class_names = sorted(df["gz2_class"].dropna().unique())
    class_to_index = {name: idx for idx, name in enumerate(class_names)}
    index_to_class = {idx: name for name, idx in class_to_index.items()}
    return class_to_index, index_to_class


def _load_and_preprocess_image(
    image_path: tf.Tensor,
    label: tf.Tensor,
) -> Tuple[tf.Tensor, tf.Tensor]:
    """Load and preprocess a single image for TensorFlow training.

    Parameters
    ----------
    image_path : tf.Tensor
        Tensor containing the image path.
    label : tf.Tensor
        Tensor containing the encoded class label.

    Returns
    -------
    Tuple[tf.Tensor, tf.Tensor]
        Preprocessed image tensor and its associated label tensor.
    """
    image_bytes = tf.io.read_file(image_path)
    image = tf.image.decode_jpeg(image_bytes, channels=3)
    image = tf.image.resize(image, IMG_SIZE)
    image = tf.cast(image, tf.float32) / 255.0
    return image, label


def _make_dataset(
    image_paths: Sequence[str],
    labels: Sequence[int],
    batch_size: int,
    training: bool,
) -> tf.data.Dataset:
    """Create a TensorFlow dataset from image paths and labels.

    Parameters
    ----------
    image_paths : Sequence[str]
        Sequence of image file paths.
    labels : Sequence[int]
        Sequence of encoded labels.
    batch_size : int
        Number of samples per batch.
    training : bool
        Whether to enable shuffling.

    Returns
    -------
    tf.data.Dataset
        TensorFlow dataset ready for model training or validation.
    """
    dataset = tf.data.Dataset.from_tensor_slices((list(image_paths), list(labels)))

    if training:
        dataset = dataset.shuffle(
            buffer_size=len(image_paths),
            reshuffle_each_iteration=True,
        )

    dataset = dataset.map(
        _load_and_preprocess_image,
        num_parallel_calls=tf.data.AUTOTUNE,
    )
    dataset = dataset.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return dataset


def _filter_missing_files(
    image_paths: Sequence[str],
    labels: Sequence[int],
) -> Tuple[list[str], list[int]]:
    """Remove samples whose image files do not exist on disk.

    Parameters
    ----------
    image_paths : Sequence[str]
        Candidate image paths.
    labels : Sequence[int]
        Candidate labels aligned with the paths.

    Returns
    -------
    Tuple[list[str], list[int]]
        Filtered paths and labels containing only valid files.
    """
    valid_paths: list[str] = []
    valid_labels: list[int] = []
    missing_count = 0

    for path_str, label in zip(image_paths, labels):
        if Path(path_str).is_file():
            valid_paths.append(path_str)
            valid_labels.append(label)
        else:
            missing_count += 1

    if missing_count > 0:
        LOGGER.warning("Ignored %d samples because image files were missing.", missing_count)

    return valid_paths, valid_labels


def create_datasets(
    batch_size: int = 32,
    val_split: float = 0.2,
    random_state: int = 42,
) -> Tuple[tf.data.Dataset, tf.data.Dataset, Dict[str, int], Dict[int, str]]:
    """Create training and validation TensorFlow datasets.

    Parameters
    ----------
    batch_size : int, optional
        Batch size used by TensorFlow.
    val_split : float, optional
        Fraction of the dataset reserved for validation.
    random_state : int, optional
        Random seed used for deterministic splitting.

    Returns
    -------
    Tuple[tf.data.Dataset, tf.data.Dataset, Dict[str, int], Dict[int, str]]
        Training dataset, validation dataset, class-to-index mapping,
        and index-to-class mapping.
    """
    if not 0.0 < val_split < 1.0:
        raise ValueError("val_split must be between 0 and 1.")

    df = load_filtered_dataframe()
    class_to_index, index_to_class = build_class_mappings(df)

    df = df.copy()
    df["label_idx"] = df["gz2_class"].map(class_to_index)

    train_df, val_df = train_test_split(
        df,
        test_size=val_split,
        random_state=random_state,
        stratify=df["label_idx"],
    )

    train_paths = train_df["image_path"].tolist()
    train_labels = train_df["label_idx"].tolist()

    val_paths = val_df["image_path"].tolist()
    val_labels = val_df["label_idx"].tolist()

    train_paths, train_labels = _filter_missing_files(train_paths, train_labels)
    val_paths, val_labels = _filter_missing_files(val_paths, val_labels)

    if not train_paths:
        raise ValueError("Training dataset is empty after filtering missing files.")

    if not val_paths:
        raise ValueError("Validation dataset is empty after filtering missing files.")

    train_dataset = _make_dataset(
        image_paths=train_paths,
        labels=train_labels,
        batch_size=batch_size,
        training=True,
    )
    val_dataset = _make_dataset(
        image_paths=val_paths,
        labels=val_labels,
        batch_size=batch_size,
        training=False,
    )

    return train_dataset, val_dataset, class_to_index, index_to_class